### ISSUE TITLE
bots kick and add

### ISSUE THREAD

**Issue by jona100x** [oylsister/ZombieSharp#34] opened 2024-06-15 18:39 UTC
I would I have done everything correctly, but when I just the server, the bot on my team and the other team just connect and disconnect very fast. And when they are doing that, I just have won after a few seconds because I instantly get points/wins. If any one knows how to fix it, please leave a comment. (it is coming with some errors in the console: [EROR] (cssharp:PluginManager) Failed to load plugin from /home/steam/cs2-dedicated/game/csgo/addons/counterstrikesharp/plugins/ZombieSharp/ZombieSharp.dll, but I don't know how to fix it)

**Comment by oylsister** [comment] 2024-07-16 09:57
the bot getting kicked is caused by mp_autoteambalance and mp_limitteams.

the error is not related the bot getting kicked, but it will be fixed in next updated

**Closed as completed by oylsister** 2024-07-16 09:57 UTC
